// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type GalleryProjectDocumentDataSlicesSlice = SinglePhotoSlice;

/**
 * Content for Gallery Project documents
 */
interface GalleryProjectDocumentData {
  /**
   * Title field in *Gallery Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre du projet
   * - **API ID Path**: gallery_project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Gallery Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<GalleryProjectDocumentDataSlicesSlice>;
}

/**
 * Gallery Project document from Prismic
 *
 * - **API ID**: `gallery_project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GalleryProjectDocumentData>,
    "gallery_project",
    Lang
  >;

export type AllDocumentTypes = GalleryProjectDocument;

/**
 * Primary content in *SinglePhoto → Default → Primary*
 */
export interface SinglePhotoSliceDefaultPrimary {
  /**
   * Photo field in *SinglePhoto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: single_photo.default.primary.photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;
}

/**
 * Default variation for SinglePhoto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SinglePhotoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SinglePhotoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SinglePhoto*
 */
type SinglePhotoSliceVariation = SinglePhotoSliceDefault;

/**
 * SinglePhoto Shared Slice
 *
 * - **API ID**: `single_photo`
 * - **Description**: SinglePhoto
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SinglePhotoSlice = prismic.SharedSlice<
  "single_photo",
  SinglePhotoSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      GalleryProjectDocument,
      GalleryProjectDocumentData,
      GalleryProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      SinglePhotoSlice,
      SinglePhotoSliceDefaultPrimary,
      SinglePhotoSliceVariation,
      SinglePhotoSliceDefault,
    };
  }
}
